### ISSUE TITLE
Instillation error

### ISSUE THREAD

**Issue by vijaygadde** [aenima-x/BlackHole#7]
Traceback (most recent call last):
  File "/opt/BlackHole/Blackhole/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 279, in execute
    saved_locale = translation.get_language()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 154, in get_language
    return _trans.get_language()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 151, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by aenima-x** [comment]
it's a django related problem. When this problem happend?
